{% set version = "1.38.16" %}

package:
  name: binaryen
  version: {{ version }}

source:
  fn: binaryen-{{ version }}.tar.gz
  url: https://github.com/WebAssembly/binaryen/archive/{{ version }}.tar.gz
  sha256: 1453d70501a8841eb8aab8c6b13eab837973c314f825a7caf8c4f2e4f21ddfd5

build:
  number: 1000
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - nodejs
    - python 2.7
  host:

test:
  commands:
    - wasm-shell --help
    - wasm-opt --help
    - wasm-merge --help
    - wasm-metadce --help
    - asm2wasm --help
    - wasm2js --help
    - wasm-emscripten-finalize --help
    - wasm-as --help
    - wasm-dis --help
    - wasm-ctor-eval --help
    - wasm-reduce --help

about:
  home: https://github.com/WebAssembly/binaryen
  license: Apache 2.0
  license_file: LICENSE
  summary: Compiler infrastructure and toolchain library for WebAssembly, in C++

extra:
  recipe-maintainers:
    - jakirkham
